//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public Action()
        {
            this.Combinations = new HashSet<Combination>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> ExpectedMonetaryValue { get; set; }
        public Nullable<decimal> ExpectedOpportunityLoss { get; set; }
    
        public virtual ICollection<Combination> Combinations { get; set; }
    }
}
