//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Combination
    {
        public Combination()
        {
            this.Parameters = new HashSet<Parameter>();
        }
    
        public int Id { get; set; }
        public int ActionId { get; set; }
        public int EventId { get; set; }
        public int TaskId { get; set; }
        public Nullable<decimal> ConditionalProfit { get; set; }
        public Nullable<decimal> WeightedProfit { get; set; }
        public Nullable<decimal> ConditionalOpportunityLoss { get; set; }
        public Nullable<decimal> WeightedOpportunityLoss { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Event Event { get; set; }
        public virtual Task Task { get; set; }
        public virtual ICollection<Parameter> Parameters { get; set; }
    }
}
