//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSSDBEntities : DbContext
    {
        public DSSDBEntities()
            : base("name=DSSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Action> Actions { get; set; }
        public DbSet<Combination> Combinations { get; set; }
        public DbSet<Constant> Constants { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Parameter> Parameters { get; set; }
        public DbSet<Task> Tasks { get; set; }
    }
}
