//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DSSDBEntities : DbContext
    {
        public DSSDBEntities()
            : base("name=DSSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Action> Actions { get; set; }
        public DbSet<Combination> Combinations { get; set; }
        public DbSet<Constant> Constants { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Parameter> Parameters { get; set; }
        public DbSet<Task> Tasks { get; set; }
    }
}
