//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterValue
    {
        public int Id { get; set; }
        public decimal Value { get; set; }
        public int ParameterId { get; set; }
        public int CombinationId { get; set; }
    
        public virtual Parameter Parameter { get; set; }
        public virtual Combination Combination { get; set; }
    }
}
