//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Combinations = new HashSet<Combination>();
            this.Constants = new HashSet<Constant>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public string Recommendation { get; set; }
    
        public virtual ICollection<Combination> Combinations { get; set; }
        public virtual ICollection<Constant> Constants { get; set; }
    }
}
