//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace DecisionSupportSystem.DbModel
{
    using System;
    using System.Collections.Generic;

    public partial class ActionParam : BasePropertyChanged, IDataErrorInfo
    {
        public Int64 Id { get; set; }
        private double _value;
        public double Value
        {
            get
            {
                return _value;
            }
            set
            {
                if (value != this._value)
                {
                    this._value = value;
                    RaisePropertyChanged("Value");
                }
            }
        }
        public Int64 ActionId { get; set; }
        public Int64? NameId { get; set; }
    
        public virtual ActionParamName ActionParamName { get; set; }
        public virtual Action Action { get; set; }
         #region реализация интерфейса IDataErrorInfo
        public string Error { get { throw new NotImplementedException(); } }

        public string this[string columnName]
        {
            get
            {
                string errormsg = null;
                if (columnName == "Value")
                {
                    
                }
                return errormsg;
            }
        }
        #endregion
    }
}
