//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CombinParam
    {
        public Int64 Id { get; set; }
        public double Value { get; set; }
        public Int64 CombinationId { get; set; }
        public Int64? NameId { get; set; }
    
        public virtual Combination Combination { get; set; }
        public virtual CombinParamName CombinParamName { get; set; }
    }
}
