//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DssDbEntities : DbContext
    {
        public DssDbEntities()
            : base("name=DssDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActionParamName> ActionParamNames { get; set; }
        public DbSet<ActionParam> ActionParams { get; set; }
        public DbSet<Action> Actions { get; set; }
        public DbSet<Combination> Combinations { get; set; }
        public DbSet<CombinParamName> CombinParamNames { get; set; }
        public DbSet<CombinParam> CombinParams { get; set; }
        public DbSet<EventParamName> EventParamNames { get; set; }
        public DbSet<EventParam> EventParams { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<TaskParamName> TaskParamNames { get; set; }
        public DbSet<TaskParam> TaskParams { get; set; }
        public DbSet<Task> Tasks { get; set; }
    }
}
