//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionSupportSystem.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task : BasePropertyChanged
    {
        public Task()
        {
            this.Combinations = new HashSet<Combination>();
            this.TaskParams = new HashSet<TaskParam>();
        }
    
        public Int64 Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public int Deleted { get; set; }
        public string TreeDiagramm { get; set; }
        private string _recomendation;
        public string Recommendation
        {
            get { return _recomendation; }
            set
            {
                if (value != this._recomendation)
                {
                    this._recomendation = value;
                    RaisePropertyChanged("Recommendation");
                }
            }
        }
        public string TaskUniq { get; set; }
        public Guid SavingId { get; set; }
        private double? _maxEmv;
        public double? MaxEmv
        {
            get { return _maxEmv; }
            set
            {
                if (value != this._maxEmv)
                {
                    this._maxEmv = value;
                    RaisePropertyChanged("MaxEmv");
                }
            }
        }

        private double? _minEol;
        public double? MinEol
        {
            get { return _minEol; }
            set
            {
                if (value != this._minEol)
                {
                    this._minEol = value;
                    RaisePropertyChanged("MinEol");
                }
            }
        }
    
        public virtual ICollection<Combination> Combinations { get; set; }
        public virtual ICollection<TaskParam> TaskParams { get; set; }
    }
}
